server:
  port: 15000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL??
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testforact?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
