server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
